### ISSUE TITLE
About an exception when i start demo

### ISSUE THREAD

**Issue by alonsoir** [alonsoir/demo-kafka-elastic#5]
I can see this exception and then the demo crash.

`demo-kafka-elastic_1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: Mapper for [lastUpdated] conflicts with existing mapping in other types:
demo-kafka-elastic_1  | [mapper [lastUpdated] has different [index] values, mapper [lastUpdated] has different [store] values, mapper [lastUpdated] has different [doc_values] values, cannot change from disabled to enabled, mapper [lastUpdated] has different [analyzer]]
demo-kafka-elastic_1  | 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
demo-kafka-elastic_1  | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepositoryViaReflection(RepositoryFactorySupport.java:383)
demo-kafka-elastic_1  | 	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactory.getTargetRepository(ElasticsearchRepositoryFactory.java:70)
demo-kafka-elastic_1  | 	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:198)
demo-kafka-elastic_1  | 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277)
demo-kafka-elastic_1  | 	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263)
demo-kafka-elastic_1  | 	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:67)
demo-kafka-elastic_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1692)
demo-kafka-elastic_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
demo-kafka-elastic_1  | 	... 62 common frames omitted
demo-kafka-elastic_1  | Caused by: java.lang.IllegalArgumentException: Mapper for [lastUpdated] conflicts with existing mapping in other types:
demo-kafka-elastic_1  | [mapper [lastUpdated] has different [index] values, mapper [lastUpdated] has different [store] values, mapper [lastUpdated] has different [doc_values] values, cannot change from disabled to enabled, mapper [lastUpdated] has different [analyzer]]
demo-kafka-elastic_1  | 	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:153)
demo-kafka-elastic_1  | 	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:115)
demo-kafka-elastic_1  | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:381)
demo-kafka-elastic_1  | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:320)
demo-kafka-elastic_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:306)
demo-kafka-elastic_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
demo-kafka-elastic_1  | 	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
demo-kafka-elastic_1  | 	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
demo-kafka-elastic_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
demo-kafka-elastic_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
demo-kafka-elastic_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
demo-kafka-elastic_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
demo-kafka-elastic_1  | 	at java.lang.Thread.run(Thread.java:748)`

See this [link](https://stackoverflow.com/questions/39077981/elasticsearch-update-mapping-conflict-exception) 

See this [link](https://github.com/elastic/elasticsearch/issues/14575)

**Comment by alonsoir** [comment]
Done, the problem was solved when i added this annotation into my test class.

`@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
`
